server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

spring:
  data:
    mongodb:
      host: localhost # MongoDB 호스트 주소
      port: 27017 # MongoDB 포트
      database: your-database-name # 사용할 데이터베이스 이름

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG # MongoDB 관련 로깅 레벨 설정