server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  data:
    mongodb:
      host: your-staging-mongodb-host
      port: your-staging-mongodb-port
      database: your-staging-database-name

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      springframework:
        data:
          mongodb: INFO # MongoDB 관련 로깅 레벨 설정